---
-
  hosts: win1
  tasks:
    - name: test Jinja if
      debug:
        msg: >
            This is test if ansible
             {% if ansible_hostname == "ANSIBLEWINSRV" -%}
                   This is ansiblewinserver
             {% elif ansible_hostname == "UBUNTU" -%}
                    This is ubuntu server
             {% endif %}