---
-
 
  # Target: where our play will run and options it will run with
  hosts: mywin1

  # Variable: variables that will apply to the play, on all target systems
  vars:
   sourcefile: "testvariable.txt"
  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: Test hostvars with an ansible fact and collect ansible_port, dot notation
      debug:
        msg: "{{ hostvars[ansible_hostname].ansible_port }}"

    - name: Test hostvars with an ansible fact and collect ansible_port, dict notation
      debug:
        msg: "{{ hostvars[ansible_hostname]['ansible_port'] }}"

  # Handlers: handlers that are executed as a notify key from a task
  
  # Roles: list of roles to be imported into the play

# Three dots indicate the end of a YAML document
...
