---
-
  hosts: win1 lin1
  gather_facts: false # this will make not to gather facts before running tasks

  vars:
    myname: "Dinesh Patil"
    company: 
       name: "Generalmills"
       location: "powai" 
  
  tasks:
    - name: Display Variable name
      debug:
        msg: >
              my name is  "{{myname}}"
              my company is "{{company}}"
              my company location is "{{company.location}}"

...