---
-
  hosts: win1 lin1
  gather_facts: true # this will make not to gather facts before running tasks

  tasks: 
    - name: Copy Files
      win_copy:
        content: "Welcome to {{ item }} ansible\n"
        dest: c:/test.txt
        with_items:
           - dinesh
           - basant
      when: ansible_distribution == "Microsoft Windows Server Datacenter"
...
